accessKey           =""
secretKey           =""
region              ="eu-west-1"
lambdaname          ="lambda-aws-ec2-start"
tagName             ="office-hours"
tagValue            ="ec-data-platform"